# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.0.0
        with: 
          deno-version: v1.x

      # Runs a single command using the runners shell
      - name: code formatting check
        run: deno fmt --check

      - name: lint
        run: deno lint
      
      - name: test
        run: deno test --allow-all --coverage=cov/
        
      - name: test coverage 
        run: deno coverage --lcov cov/ > cov.local
